### ISSUE TITLE
Why this method called zero-shot semantic segmentation?

### ISSUE THREAD

**Issue by ChunmengLiu1** [blumenstiel/MESS#5]
Hi! Thanks for your great effort!

The methods you compared in the paper are from open vocabulary semantic segmentation. I feel confused about whether they know class information or not during inference. If they know class information, it seems like weakly supervised semantic segmentation. So I want to know why these methods are called zero-shot semantic segmentation. 

Thank you for your help! I'm looking forward to your reply!

**Comment by blumenstiel** [comment]
Thanks for your interest!

IMHO the terms "zero-shot" and "open-vocabulary" are not clearly defined in semantic segmentation and we discussed quite long which term to use for our work. We ended up using "zero-shot" because of multiple reasons:
- The latest research on zero-shot is often studying "generalized zero-shot" where classes can be present during pre-training (i.e. in CLIP) but the current task is not (defined through the specific set of classes). This is the definition we used in our work.
- In object detection, "open-vocabulary" is sometimes defined as an in-domain task while we are explicitly testing cross-domain performance. It is not defined in semantic segmentation, but you could argue that "open-vocabulary" models are trained to be used within the same domain.
- "open-vocabulary" is a relative new term in CS while "zero-shot" is well known.

Note that every zero-shot model needs to learn semantic information about many classes to be useful. But the models are not trained to do semantic segmentation on these classes, so this part is clearly zero-shot.

**Comment by ChunmengLiu1** [comment]
Thanks so much!!!
